use alloy::consensus::Transaction as TransactionTrait;
use alloy::network::TransactionResponse;
use alloy::primitives::{Address, B256, U256, b256};
use alloy::rpc::types::transaction::Transaction as AlloyTransaction;
use anyhow::{Context, Result};
use chrono::Utc;
use common::types::{
    Block, Contract, Log, ProcessedBlock, RawBlockData, TokenTransfer, Transaction,
};
use tokio::sync::mpsc::{Receiver, Sender};

pub struct Processor {
    pub block_receiver: Receiver<RawBlockData>,
    pub processed_block_sender: Sender<ProcessedBlock>,
}

impl Processor {
    pub async fn run(&mut self) -> Result<()> {
        while let Some(block) = self.block_receiver.recv().await {
            let processed_block = self.process_block(block).await?;
            self.processed_block_sender
                .send(processed_block)
                .await?;
        }
        Ok(())
    }
    pub async fn process_block(&self, raw_block_data: RawBlockData) -> Result<ProcessedBlock> {
        let raw_block = raw_block_data.raw_block;
        let receipts = raw_block_data.tx_receipts;
        let transactions: Vec<Transaction> = raw_block
            .transactions
            .clone()
            .into_transactions()
            .zip(receipts.clone().into_iter())
            .map(|(tx, receipt)| -> Result<Transaction> {
                Ok(Transaction {
                    hash: tx
                        .block_hash
                        .context("missing block_hash")?,
                    block_number: Some(
                        tx.block_number
                            .context("missing block_number")? as i64,
                    ),
                    tx_index: tx
                        .transaction_index
                        .context("missing tx_index")? as i32,
                    from_addr: tx.inner.signer(),
                    to_addr: tx.inner.to(),
                    value: tx.value(),
                    gas_used: receipt.gas_used as i64,
                    gas_price: TransactionTrait::gas_price(&tx).unwrap_or(0) as i64,
                    gas_limit: tx.gas_limit() as i64,
                    input: Some(tx.input().clone()),
                    nonce: tx.nonce() as i64,
                    status: Some(receipt.status() as i16),
                    created_at: Utc::now(),
                })
            })
            .collect::<Result<Vec<_>, _>>()?;
        let logs: Vec<Log> = receipts
            .iter()
            .flat_map(|receipt| {
                receipt.logs().iter().map(|log| {
                    let topics = log.topics();
                    Log {
                        id: 0, // auto-generated by DB
                        block_number: raw_block.header.number as i64,
                        tx_hash: log.transaction_hash,
                        log_index: log.log_index.unwrap_or(0) as i32,
                        address: log.address(),
                        topic0: topics.first().copied(),
                        topic1: topics.get(1).copied(),
                        topic2: topics.get(2).copied(),
                        topic3: topics.get(3).copied(),
                        data: Some(log.data().data.clone()),
                    }
                })
            })
            .collect();
        // Transfer(address,address,uint256)
        const TRANSFER_SIG: B256 =
            b256!("ddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef");

        let token_transfers: Vec<TokenTransfer> = logs
            .iter()
            .filter(|log| log.topic0 == Some(TRANSFER_SIG))
            .filter_map(|log| {
                let from_topic = log.topic1?;
                let to_topic = log.topic2?;

                // ERC-721: value in topic3, ERC-20: value in data
                let (value, token_id, token_type) = if let Some(topic3) = log.topic3 {
                    // ERC-721: tokenId in topic3
                    (U256::ZERO, U256::from_be_bytes(topic3.0), 721)
                } else {
                    // ERC-20: value in data
                    let data = log.data.as_ref()?;
                    let value = U256::from_be_slice(data);
                    (value, U256::ZERO, 20)
                };

                Some(TokenTransfer {
                    id: 0,
                    block_number: log.block_number,
                    tx_hash: log.tx_hash,
                    log_index: log.log_index,
                    token_address: log.address,
                    from_addr: Address::from_slice(&from_topic[12..]),
                    to_addr: Address::from_slice(&to_topic[12..]),
                    value,
                    token_id,
                    token_type,
                })
            })
            .collect();
        let contracts: Vec<Contract> = raw_block
            .transactions
            .clone()
            .into_transactions()
            .zip(receipts.iter())
            .filter(|(tx, _)| tx.inner.to().is_none())
            .filter_map(|(tx, receipt)| {
                Some(Contract {
                    address: receipt.contract_address?,
                    creator: tx.inner.signer(),
                    creation_tx: Some(tx.tx_hash()),
                    bytecode: Some(tx.input().clone()),
                    is_verified: Some(false),
                    name: None,
                    source_code: None,
                    abi: None,
                    compiler: None,
                    optimization: None,
                    created_at: Some(Utc::now()),
                })
            })
            .collect();
        let processed_block = ProcessedBlock {
            block: raw_block.into(),
            transactions,
            logs,
            token_transfers,
            contracts,
        };

        Ok(processed_block)
    }
}
